FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
# linux-arm64
ARG platform=win-x64
WORKDIR /app

# context should be in solution root
# copy everything else and build app
COPY . ./
RUN dotnet publish ./Apps/PRR/PRR.API.Auth/PRR.API.Auth.fsproj -c Release -o out -r ${platform}

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "PRR.API.Auth.dll"]