config:
  k8s:Auth__Jwt__AccessTokenSecret: f2EW%LKWew+eUp*8+SS*Nz3mtE
  k8s:adminApp_Port: "70"
  k8s:adminApp_TargetPort: "80"
  k8s:api_ENV_ASPNETCORE_ENVIRONMENT: QA-K8S
  k8s:api_ENV_Auth__Jwt__AccessTokenSecret: $L@-Qcu6R$QWU#MvhC85Wk
  k8s:api_ENV_Auth__Jwt__IdTokenSecret: 7PgS9ThTfM347DPm6@m#+2
  k8s:api_ENV_Auth__PasswordSecret: 3Q^R4*s7dG*&&x?^Y+%j!r
  k8s:api_ENV_Auth__PerimeterSocialProviders__Github__ClientId:
    secure: AAABAMVGJDwipASlZU/laugi5rnsxMho3/fZK0SiSVwlYs+bujprsleGpTuyS0LNxTfkUg==
  k8s:api_ENV_Auth__PerimeterSocialProviders__Github__SecretKey:
    secure: AAABADmKdtiKV5QJGoQ61R8LcraXbiPo5wkQBiejIdHIfJ6qcO7C5J1rIHFCXP1/rOoPgjL1FJgxeHMjubfu5xlUC0aUp/44
  k8s:api_ENV_Auth__PerimeterSocialProviders__Google__ClientId:
    secure: AAABAOJJ3Cnle3XPaCRqwf69DoBKBzd7WDDd2uGKKbOpqC8ndzlhJTi0M1dWDnVgQsl69a+pgj84op6ab0XRIhCcecaz90d/CdcpwMFZpDSQC0114y7o2mjmyaUMUOMjLeIRV99Xf3M=
  k8s:api_ENV_Auth__PerimeterSocialProviders__Google__SecretKey:
    secure: AAABAA0H0yk1ZvxcCgquHWAQ08sY05sOXgMaxOj6o9wDZhPmWVO3vvBhidS7KhutJgYJBt87GMU=
  k8s:api_ENV_Auth__PerimeterSocialProviders__Twitter__ClientId: 67KuSYwPHVTL6UwV7MLLPBrEB
  k8s:api_ENV_Auth__PerimeterSocialProviders__Twitter__SecretKey: rf8iVsl0F3hGVIGpwdcsHMyNH5lxLYHv7LhC7FCEF1wnbwwLJP
  k8s:api_ENV_Auth__Social__CallbackExpiresInMilliseconds: "300000"
  k8s:api_ENV_Auth__Social__CallbackUrl: https://prr.pw/api/auth/social/callback
  k8s:api_ENV_ConnectionStrings__PostgreSQL: Host=psql;Database=prr_qa;Username=postgres;Password=123;
  k8s:api_ENV_Logging__Elastic__ServiceUrl: http://elastic:9200
  k8s:api_ENV_MailGun__ApiKey: 8aafb733c50135fe6bac243ebfc2a252-4de08e90-8da900ea
  k8s:api_ENV_MailGun__DomainName: www.perimeter.pw
  k8s:api_ENV_MailGun__Region: EU
  k8s:api_ENV_MailSender__FromEmail: info@perimeter.pw
  k8s:api_ENV_MailSender__FromName: Perimeter (alpha)
  k8s:api_ENV_MailSender__Project__BaseUrl: http://prr.pw
  k8s:api_ENV_MailSender__Project__Name: Perimeter (alpha)
  k8s:api_ENV_MongoKeyValueStorage__ConnectionString: mongodb://root:123@mongo?authSource=admin
  k8s:api_ENV_MongoViewStorage__ConnectionString: mongodb://root:123@mongo?authSource=admin
  k8s:api_ENV_ServiceBus__Host: rabbit
  k8s:api_ENV_TenantAuth__AccessTokenSecret: VR4%2nws=PN5j!W!3uJ!NS
  k8s:api_ENV_Tracing__Jaeger__AgentHost: jaeger
  k8s:auth_api_Port: "81"
  k8s:auth_api_TargetPort: "5000"
  k8s:idpApp_Port: "80"
  k8s:idpApp_TargetPort: "80"
  k8s:mongo_MONGODB_ROOT_PASSWORD: "123"
  k8s:mongo_MONGODB_ROOT_USER: root
  k8s:mongo_dataPath: /data/prr/mongo
  k8s:mongo_storageSize: "5"
  k8s:psql_POSTGRES_DB: prr-qa
  k8s:psql_POSTGRES_PASSWORD: "123"
  k8s:psql_POSTGRES_USER: postgres
  k8s:psql_dataPath: /data/prr/psql
  k8s:psql_storageSize: "5"
  k8s:registryPassword:
    secure: AAABAFnVDK81AG4GlzYjFuMJblUL3j4OBe3kJsYWNSLTMJFQosvvPC9e
  k8s:registryServer: docker.io
  k8s:registryUsername: baio
  k8s:tenant_api_Port: "82"
  k8s:tenant_api_TargetPort: "6000"
