config:
  k8s:Auth__Jwt__AccessTokenSecret: kkkkkkkkkkkkkkk
  k8s:adminApp_Port: "70"
  k8s:adminApp_TargetPort: "80"
  k8s:api_ENV_ASPNETCORE_ENVIRONMENT: LOCAL-K8S
  k8s:api_ENV_Auth__Jwt__AccessTokenSecret: aaaaaaaaaa
  k8s:api_ENV_Auth__Jwt__IdTokenSecret: bbbbbbbbbbb
  k8s:api_ENV_Auth__PasswordSecret: ccccccccccccccccccc
  k8s:api_ENV_Auth__PerimeterSocialProviders__Github__ClientId:
    secure: AAABAIKNyn7zoQY0y/OPleirIMI7QdQq6Uwl/bDouC5CVw02J38OFnMSB4t+HSKTRjBvMw==
  k8s:api_ENV_Auth__PerimeterSocialProviders__Github__SecretKey:
    secure: AAABAJxv22ilYMfP1hhyAtDbzNcF1Va/HlvwK+15Wg862etM3W+Q67j4J5lwcCWwn64wVjXXvlCzeshwyRSTZpzviLJ6Tlj+
  k8s:api_ENV_Auth__PerimeterSocialProviders__Google__ClientId:
    secure: AAABALoD41myQXS273b+TGfLMXeaE1Zz+BSbBg5tayaI+eqnCMly9IEZtwlI0TFxhyBKL0OTykkXqlq9zgsR6zKhR9ePlu2nYPGUQr0j6ky9nq5EGvRoRdpLoSOcNcmHvrYTYwxJ0H8=
  k8s:api_ENV_Auth__PerimeterSocialProviders__Google__SecretKey:
    secure: AAABAK9A4aUZ3jXLqGLdDoYFJc1+mqJ4GPXcXQ13P8smHTL6FToQ9LQ9FmeYe703/6xctZSz6Zo=
  k8s:api_ENV_Auth__PerimeterSocialProviders__Twitter__ClientId: 67KuSYwPHVTL6UwV7MLLPBrEB
  k8s:api_ENV_Auth__PerimeterSocialProviders__Twitter__SecretKey: rf8iVsl0F3hGVIGpwdcsHMyNH5lxLYHv7LhC7FCEF1wnbwwLJP
  k8s:api_ENV_Auth__Social__CallbackExpiresInMilliseconds: 300000
  k8s:api_ENV_Auth__Social__CallbackUrl: https://prr.pw/api/auth/social/callback
  k8s:api_ENV_ConnectionStrings__PostgreSQL:  Host=psql;Database=prr_qa;Username=postgres;Password=123;
  k8s:api_ENV_Logging__Elastic__ServiceUrl: ""
  k8s:api_ENV_Tracing__Jaeger__AgentHost: ""
  k8s:api_ENV_MailGun__ApiKey: 8aafb733c50135fe6bac243ebfc2a252-4de08e90-8da900ea
  k8s:api_ENV_MailGun__DomainName: www.perimeter.pw
  k8s:api_ENV_MailGun__Region: EU
  k8s:api_ENV_MailSender__FromEmail: Perimeter (local)
  k8s:api_ENV_MailSender__FromName: Perimeter (local)
  k8s:api_ENV_MailSender__Project__BaseUrl: http://perimeter-local:9801
  k8s:api_ENV_MailSender__Project__Name: Perimeter (stage)
  k8s:api_ENV_MongoKeyValueStorage__ConnectionString: mongodb://root:123@mongo?authSource=admin
  k8s:api_ENV_MongoViewStorage__ConnectionString: mongodb://root:123@mongo?authSource=admin
  k8s:api_ENV_ServiceBus__Host: amqp://rabbit
  k8s:api_ENV_TenantAuth__AccessTokenSecret: zzzzzzzzzzzzzzzzzzz
  k8s:auth_api_Port: "81"
  k8s:auth_api_TargetPort: "5000"
  k8s:idpApp_Port: "80"
  k8s:idpApp_TargetPort: "80"
  k8s:mongo_MONGODB_ROOT_PASSWORD: "123"
  k8s:mongo_MONGODB_ROOT_USER: root
  k8s:mongo_dataPath: /C/dev/data/prr/mongo
  k8s:mongo_storageSize: "1"
  k8s:psql_POSTGRES_DB: prr-dev
  k8s:psql_POSTGRES_PASSWORD: "123"
  k8s:psql_POSTGRES_USER: postgres
  k8s:psql_dataPath: /C/dev/data/prr/psql
  k8s:psql_storageSize: "1"
  k8s:registryServer: docker.io
  k8s:registryUsername: baio
  k8s:tenant_api_Port: "82"
  k8s:tenant_api_TargetPort: "6000"
