FROM node:12.20-alpine AS build-image
WORKDIR /app
COPY decorate-angular-cli.js package.json yarn.lock ./
RUN yarn install --frozen-lockfile

ENV PATH="./node_modules/.bin:$PATH" 

COPY . ./
RUN ng build admin --prod --configuration qa-k8s

FROM nginx
COPY .config/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-image /app/dist/apps/admin /usr/share/nginx/html