FROM node:14.15.5-alpine AS build-image
WORKDIR /app
COPY decorate-angular-cli.js package.json yarn.lock  npm-shrinkwrap.json ./
RUN npm install

ENV PATH="./node_modules/.bin:$PATH" 

COPY . ./
RUN ng build idp --prod --configuration qa-k8s

FROM nginx
COPY .config/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-image /app/dist/apps/idp /usr/share/nginx/html