FROM node:12.20-alpine AS build-image
WORKDIR /app
COPY decorate-angular-cli.js package.json yarn.lock ./
RUN yarn set version berry
RUN yarn install --immutable
#RUN yarn install --frozen-lockfile

ENV PATH="./node_modules/.bin:$PATH" 

COPY . ./
RUN ng build idp --prod --configuration qa-k8s

FROM nginx
COPY .config/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-image /app/dist/apps/idp /usr/share/nginx/html